### ISSUE TITLE
Weird issue with regex and Eos()

### ISSUE THREAD

**Issue by jtravs** [andrewcooke/ParserCombinator.jl#13]
I'm testing a simple Boolean regex:
```julia
julia> parse_one("false", p"([Tt][Rr][Uu][Ee])|([Ff][Aa][Ll][Ss][Ee])"+Eos())
1-element Array{Any,1}:
 "false"
```
works fine, but this is weird:
```julia
julia> parse_one("true", p"([Tt][Rr][Uu][Ee])|([Ff][Aa][Ll][Ss][Ee])"+Eos())
ERROR: ParserCombinator.ParserException("cannot parse")
 in once at /Users/john/.julia/v0.5/ParserCombinator/src/core/parsers.jl:184
 [inlined code] from /Users/john/.julia/v0.5/ParserCombinator/src/core/parsers.jl:169
 in single_result at /Users/john/.julia/v0.5/ParserCombinator/src/core/parsers.jl:193
 in eval at ./boot.jl:264
```
Without the `Eos()` it works:
```julia
julia> parse_one("true", p"([Tt][Rr][Uu][Ee])|([Ff][Aa][Ll][Ss][Ee])")
1-element Array{Any,1}:
 "true"
```
Any ideas?

P.S. Thanks for a great library!

**Comment by andrewcooke** [comment]
```
julia> parse_one("true", p"([Tt][Rr][Uu][Ee]|[Ff][Aa][Ll][Ss][Ee])"+Eos())
1-element Array{Any,1}:                                                         
 "true"
```

(note the change in how parens are used in the middle).

However, I'm still trying to work out *why*.

**Comment by andrewcooke** [comment]
ah.  ok, so yes, it's a bug, sorry.

i need to know where the regex ends, so that i can skip that many characters.  so i append a (.??) to the end of the regexp, which i then use to find the length.  that *assumes* that what it is appended to is a single match, not alternatives.

the fix is to surround the regexp in `(?:    )`, so if the original pattern is `XXX` then what is matched "behind the scenes" is `(?:XXX)(.??)`.  that seems to work.

i'm adding some tests and then will push a new release.

**Comment by andrewcooke** [comment]
huh.  had no idea a commit to github could actually close an issue automatically.

anyway, this is now tagged as 1.7.4 and pending release is at https://github.com/JuliaLang/METADATA.jl/pull/4284

**Comment by jtravs** [comment]
Great! Thanks for the amazingly fast response!

**Comment by andrewcooke** [comment]
no problem (the speed was just luck - lazy sunday morning with nothing happening...)
